Vagrant.configure("2") do |config|
  # Configuración de la máquina (Debian 12)
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "mirror.sistema.sol"
  config.vm.network "private_network", ip: "192.168.56.10"

 
  config.vm.provision "ansible" do |ansible|

    ansible.playbook = "provision/playbook_anonimo.yml" 
  end
end