Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"


  config.vm.define "servidor" do |s|
    s.vm.hostname = "ftp.example.test"
    s.vm.network "private_network", ip: "192.168.56.10"
   
    s.vm.network "forwarded_port", guest: 21, host: 2121 
    

    s.vm.provision "shell", path: "provision/servidor.sh"
  end


  config.vm.define "cliente" do |c|
    c.vm.hostname = "cliente"
    c.vm.network "private_network", ip: "192.168.56.20"
    

    c.vm.provision "shell", path: "provision/cliente.sh"
  end
end